root: true
env:
  es2022: true
parserOptions:
  ecmaVersion: latest
extends:
  - 'eslint:recommended'
  # FIXME: https://github.com/vuejs/create-vue/issues/123
  # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  # - 'plugin:@typescript-eslint/strict'
  - 'plugin:vue/vue3-recommended'
  - '@vue/eslint-config-typescript/recommended'
  - '@vue/eslint-config-airbnb-with-typescript'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - '@vue/eslint-config-prettier'
settings:
  import/internal-regex: ^@/
rules:
  # Prettier
  prettier/prettier: error

  # Import
  import/order:
    - error
    - groups:
        - builtin
        - type
        - external
        - object
        - internal
        - parent
        - sibling
        - index
        - unknown
      pathGroups:
        - pattern: '@/**/*.vue'
          group: internal
          position: after
      newlines-between: always
      alphabetize:
        order: asc
        orderImportKind: asc
      warnOnUnassignedImports: true

  # Override Airbnb:
  no-useless-computed-key: off # error in eslint-config-airbnb-base/rules/es6.js
  no-shadow: off # error in eslint-config-airbnb-base/rules/variables.js
  object-shorthand: # airbnb 3.3,3.4
    - error
    - always
    - ignoreConstructors: false
      avoidQuotes: false # true in airbnb
  func-style: # airbnb 7.1
    - error
    - declaration
    - allowArrowFunctions: true
  no-param-reassign: # airbnb 7.12
    - error
    - props: false # true in airbnb
  import/prefer-default-export: off # airbnb 10.6: error

  # Override Vue:
  vue/block-tag-newline: error
  vue/component-name-in-template-casing:
    - error
    - PascalCase
    - registeredComponentsOnly: false
  vue/custom-event-name-casing: error
  vue/match-component-file-name:
    - error
    - extensions: ['jsx', 'tsx', 'vue']
      shouldMatchCase: true
  vue/next-tick-style: error
  # vue/no-bare-strings-in-template: warn # enable when i18n
  vue/no-empty-component-block: error
  vue/no-multiple-objects-in-class: error
  vue/no-potential-component-option-typo: error
  vue/no-reserved-component-names:
    - error
    - disallowVueBuiltInComponents: true
      disallowVue3BuiltInComponents: true
  vue/no-useless-mustaches:
    - error
    - ignoreIncludesComment: false
      ignoreStringEscape: true
  vue/no-useless-v-bind:
    - error
    - ignoreIncludesComment: false
      ignoreStringEscape: true
  vue/padding-line-between-blocks: error
  vue/require-direct-export: error
  vue/require-name-property: error
  vue/v-for-delimiter-style: error
  vue/v-on-event-hyphenation: error
  vue/v-on-handler-style:
    - error
    - inline
  # vue/block-lang
